import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {IdleInstaller,INSTALL_KEY,releaseFiles,sha256,validateInstallationFolder} from '../ChatGPT-Exporter-English-Edge/installer.mjs';
import {setupUpdates} from '../ChatGPT-Exporter-English-Edge/update-ui.mjs';
const Zip=createRequire(import.meta.url)('../ChatGPT-Exporter-English-Edge/jszip.min.js'),enc=s=>new TextEncoder().encode(s),dec=b=>new TextDecoder().decode(b);
function disk(seed={}){const files=new Map(Object.entries(seed).map(([k,v])=>[k,enc(v)])),fail={path:null};function directory(prefix=''){return {name:'extension',queryPermission:async()=> 'granted',getDirectoryHandle:async(name,{create=false}={})=>{const p=prefix+name+'/';if(!create&&![...files.keys()].some(k=>k.startsWith(p)))throw new DOMException('missing','NotFoundError');return directory(p);},getFileHandle:async(name,{create=false}={})=>{const p=prefix+name;if(!create&&!files.has(p))throw new DOMException('missing','NotFoundError');return {getFile:async()=>new Blob([files.get(p)]),createWritable:async()=>{let bytes;return {write:async value=>{if(fail.path===p){fail.path=null;throw Error('simulated disk failure');}bytes=value;},close:async()=>files.set(p,new Uint8Array(bytes)),abort:async()=>{}};}};},removeEntry:async name=>files.delete(prefix+name)};}return {root:directory(),files,fail};}
function fixture(){const d=disk({'manifest.json':'old manifest','app.mjs':'old app','extra-viewer.mjs':'preserve extra'}),baseline=new Map([...d.files].filter(([p])=>p!=='extra-viewer.mjs')),next=new Map([['manifest.json',enc('new manifest')],['app.mjs',enc('new app')],['new.mjs',enc('new module')]]);let record={root:d.root},idle=true,reloads=0,loads=0,blocked=false;const messages=[],installer=new IdleInstaller({db:{get:async()=>record,put:async(store,key,value)=>{assert.equal(key,INSTALL_KEY);record={...value,journal:value.journal?structuredClone(value.journal):undefined};}},runtime:{getManifest:()=>({version:'2.4.17'}),reload:()=>reloads++},isIdle:()=>idle,block:v=>blocked=v,validate:async()=>true,load:async v=>{loads++;return {files:v==='2.4.17'?baseline:next};},onStatus:s=>messages.push(s)});return {...d,installer,baseline,next,messages,record:()=>record,idle:v=>idle=v,reloads:()=>reloads,loads:()=>loads,blocked:()=>blocked};}
const available={autoInstall:true,available:true,latestVersion:'2.4.18'};
test('interrupted rollback with lost permission keeps backup blocked but allows original-folder regrant',async()=>{const manifest={name:'ChatGPT Exporter — English Autopilot',version:'2.4.17'},d=disk({'manifest.json':JSON.stringify(manifest),'app.mjs':'partial','.exporter-rollback/old/app.mjs':'restored','.exporter-rollback/old/manifest.json':JSON.stringify(manifest)});let record={root:d.root,journal:{backup:'.exporter-rollback/old',paths:['app.mjs','manifest.json'],added:[]}},blocked=false,deny=true;const originalDir=d.root.getDirectoryHandle;d.root.getDirectoryHandle=async(...args)=>{if(deny)throw new DOMException('permission lost','NotAllowedError');return originalDir(...args);};d.root.isSameEntry=async root=>root===d.root;
 const nodes=new Map(),document={getElementById:id=>{if(!nodes.has(id))nodes.set(id,{checked:false,listeners:{},addEventListener(type,fn){this.listeners[type]=fn;}});return nodes.get(id);}},saved={timer:globalThis.setInterval,picker:globalThis.showDirectoryPicker,fetch:globalThis.fetch};globalThis.setInterval=()=>0;globalThis.showDirectoryPicker=async()=>d.root;globalThis.fetch=async url=>new Response(d.files.get(url.split('/').at(-1)));try{await setupUpdates(document,{getManifest:()=>manifest,getURL:p=>'https://extension.test/'+p,onMessage:{addListener(){}},sendMessage:async()=>({ok:true,state:{interval:'off',autoInstall:false}})},manifest.version,{db:{get:async()=>record,put:async(s,k,value)=>record=value},isIdle:()=>false,block:v=>blocked=v});assert.equal(blocked,true);assert.match(nodes.get('extension-install-status').textContent,/original installation folder/);deny=false;await nodes.get('extension-install-folder').listeners.click();assert.equal(blocked,false);assert.equal(record.journal,undefined);assert.equal(dec(d.files.get('app.mjs')),'restored');}finally{globalThis.setInterval=saved.timer;globalThis.showDirectoryPicker=saved.picker;globalThis.fetch=saved.fetch;}
});
test('silent installation defaults off, waits for idle and coalesces concurrent turns',async()=>{const f=fixture();await f.installer.turn({...available,autoInstall:false});f.idle(false);await f.installer.turn(available);assert.equal(f.loads(),0);f.idle(true);await Promise.all([f.installer.turn(available),f.installer.turn(available)]);assert.equal(f.loads(),2);assert.equal(f.reloads(),1);assert.equal(dec(f.files.get('app.mjs')),'new app');assert.equal(dec(f.files.get('extra-viewer.mjs')),'preserve extra');assert.equal(f.blocked(),false);assert.equal(f.record().lastInstall.to,'2.4.18');assert.equal(f.record().journal,undefined);assert.equal(dec(f.files.get(f.record().lastInstall.backup+'/app.mjs')),'old app');});
test('local Viewer edits defer installation before writes and do not repeatedly download',async()=>{const f=fixture();f.files.set('app.mjs',enc('old app + local Viewer integration'));await f.installer.turn(available);await f.installer.turn(available);assert.equal(f.loads(),2);assert.equal(f.reloads(),0);assert.equal(dec(f.files.get('app.mjs')),'old app + local Viewer integration');assert.match(f.messages.at(-1),/Viewer changes/);assert.equal([...f.files.keys()].some(p=>p.startsWith('.exporter-rollback')),false);});
test('partial write failure restores old bytes, removes only newly added files and retains rollback',async()=>{const f=fixture();f.fail.path='manifest.json';await f.installer.turn(available);assert.equal(f.reloads(),0);assert.equal(dec(f.files.get('app.mjs')),'old app');assert.equal(dec(f.files.get('manifest.json')),'old manifest');assert.equal(f.files.has('new.mjs'),false);assert.equal(f.files.has('extra-viewer.mjs'),true);assert.equal(f.record().journal,undefined);assert.match(f.messages.at(-1),/simulated disk failure/);});
test('persisted interrupted checkpoint restores on reopening even without an update',async()=>{const f=fixture();f.files.set('.exporter-rollback/old/app.mjs',enc('old app'));f.files.set('app.mjs',enc('partially updated'));f.files.set('.exporter-rollback/old/manifest.json',enc('old manifest'));await f.installer.recover({root:f.root,journal:{backup:'.exporter-rollback/old',paths:['app.mjs','manifest.json'],added:[]}});assert.equal(dec(f.files.get('app.mjs')),'old app');assert.equal(f.record().journal,undefined);});
test('permission loss and conflicting newly introduced paths leave local data untouched',async()=>{const f=fixture();f.root.queryPermission=async()=> 'denied';await f.installer.turn(available);assert.equal(f.loads(),0);assert.match(f.messages.at(-1),/permission expired/);const g=fixture();g.files.set('new.mjs',enc('local unrelated module'));await g.installer.turn(available);assert.equal(g.reloads(),0);assert.equal(dec(g.files.get('new.mjs')),'local unrelated module');assert.match(g.messages.at(-1),/conflicts/);});
test('choosing a different folder fails loaded-resource probe and removes only its probe',async()=>{const manifest={name:'ChatGPT Exporter — English Autopilot',version:'2.4.17'},d=disk({'manifest.json':JSON.stringify(manifest),'app.mjs':'keep'});const original=globalThis.fetch;globalThis.fetch=async function(){assert.equal(this,globalThis);return new Response('wrong');};try{await assert.rejects(()=>validateInstallationFolder(d.root,{getManifest:()=>manifest,getURL:p=>'https://example.test/'+p}),/not the loaded/);}finally{globalThis.fetch=original;}assert.deepEqual([...d.files.keys()],['manifest.json','app.mjs']);});
test('official bounded package is checksum verified; corrupt bytes and traversal rejected',async()=>{const version='2.4.18',base='https://github.com/kitomisaitichi-design/chatgpt-exporter',name=`ChatGPT-Exporter-English-Edge-v${version}.zip`,url=`${base}/releases/download/ChatGPT${version}/${name}`,manifest={manifest_version:3,name:'ChatGPT Exporter — English Autopilot',version,background:{service_worker:'background.js'},icons:{}};
 async function packageFor(unsafe=false){const z=new Zip();for(const p of ['app.mjs','core.mjs','exporter.html','jszip.min.js','background.js'])z.file('ChatGPT-Exporter-English-Edge/'+p,'sample');z.file('ChatGPT-Exporter-English-Edge/manifest.json',JSON.stringify(manifest));if(unsafe)z.file('ChatGPT-Exporter-English-Edge/../escape.txt','bad');return z.generateAsync({type:'uint8array'});}
 let bytes=await packageFor(),sum=await sha256(bytes);const fetch=async path=>path.endsWith('.sha256.txt')?new Response(sum+'  '+name):path.endsWith('.zip')?new Response(bytes):Response.json({tag_name:'ChatGPT'+version,html_url:base+'/releases/tag/ChatGPT'+version,assets:[{name,browser_download_url:url},{name:name+'.sha256.txt',browser_download_url:url+'.sha256.txt'}]});const original=globalThis.fetch;let nativeCalls=0;globalThis.fetch=function(...args){assert.equal(this,globalThis);nativeCalls++;return fetch(...args);};try{assert.equal((await releaseFiles(version,{Zip})).files.size,6);assert.equal(nativeCalls,3);}finally{globalThis.fetch=original;}sum='0'.repeat(64);await assert.rejects(()=>releaseFiles(version,{Zip,fetch}),/checksum/);bytes=await packageFor(true);sum=await sha256(bytes);await assert.rejects(()=>releaseFiles(version,{Zip,fetch}),/Unsafe release path/);
});
