import test from 'node:test';
import assert from 'node:assert/strict';
import {UpdateChecker,UPDATE_KEY,UPDATE_ALARM,UPDATE_INTERVALS,newerVersion} from '../ChatGPT-Exporter-English-Edge/updates.mjs';
function fixture(options={}){let time=10000,requests=0,data={},alarms=new Map();const checker=new UpdateChecker({storage:{get:async key=>({[key]:structuredClone(data[key])}),set:async values=>Object.assign(data,structuredClone(values))},alarms:{clear:async name=>alarms.delete(name),create:async(name,alarm)=>alarms.set(name,alarm)},version:'2.4.17',now:()=>time,fetch:async(...args)=>{requests++;return options.fetch?options.fetch(...args):Response.json({tag_name:'ChatGPT2.4.18',html_url:'https://github.com/kitomisaitichi-design/chatgpt-exporter/releases/tag/ChatGPT2.4.18'},{headers:{etag:'fixture-etag'}});}});return {checker,alarms,data,requests:()=>requests,advance:ms=>time+=ms};}
test('silent install is independently opt-in and persists without changing the check schedule',async()=>{const f=fixture();assert.equal((await f.checker.status()).autoInstall,false);await f.checker.setInterval('off');await f.checker.setAutoInstall(true);f.checker.ready=null;assert.equal((await f.checker.status()).autoInstall,true);assert.equal((await f.checker.status()).interval,'off');assert.equal(f.alarms.size,0);await f.checker.setAutoInstall(false);assert.equal(f.data[UPDATE_KEY].autoInstall,false);});
test('24h default, all intervals and off survive worker initialization without chat state',async()=>{const f=fixture();await f.checker.initialize();assert.equal(f.data[UPDATE_KEY].interval,'24h');for(const option of ['12h','24h','week','off']){const result=await f.checker.setInterval(option);assert.equal(result.nextCheckAt,option==='off'?0:10000+UPDATE_INTERVALS[option]);assert.equal(f.alarms.has(UPDATE_ALARM),option!=='off');}f.checker.ready=null;await f.checker.initialize();await f.checker.check();assert.equal(f.requests(),0);assert.deepEqual(Object.keys(f.data),[UPDATE_KEY]);});
test('manual check works with schedule off and publishes only a newer official release',async()=>{const f=fixture();await f.checker.setInterval('off');const result=await f.checker.check({manual:true});assert.equal(result.available,true);assert.equal(result.latestVersion,'2.4.18');assert.equal(result.lastCheckedAt,10000);assert.equal(f.alarms.size,0);assert.equal(f.requests(),1);assert.equal(newerVersion('2.4.9','2.4.17'),false);assert.equal(newerVersion('2.10.0','2.9.99'),true);assert.equal(newerVersion('bad','2.4.17'),false);});
test('overlapping checks share one request; ETag304 keeps release and advances successful check',async()=>{let release;const f=fixture({fetch:()=>new Promise(r=>release=r)});const a=f.checker.check({manual:true}),b=f.checker.check({manual:true});await new Promise(r=>setTimeout(r,0));assert.equal(f.requests(),1);release(Response.json({tag_name:'ChatGPT2.4.18',html_url:'https://github.com/kitomisaitichi-design/chatgpt-exporter/releases/tag/ChatGPT2.4.18'},{headers:{etag:'test'}}));await Promise.all([a,b]);f.advance(1000);f.checker.fetch=async(url,args)=>{assert.equal(args.headers['If-None-Match'],'test');return new Response(null,{status:304});};const result=await f.checker.check();assert.equal(result.available,true);assert.equal(result.lastCheckedAt,11000);});
test('network errors retry after one hour without erasing known release or backup state',async()=>{const f=fixture();await f.checker.check();f.checker.fetch=async()=>{throw Error('offline');};const result=await f.checker.check();assert.equal(result.lastError,'offline');assert.equal(result.latestVersion,'2.4.18');assert.equal(result.nextCheckAt,10000+3600000);assert.equal(result.lastCheckedAt,10000);});
test('unexpected release URL/prerelease never becomes an update notice',async()=>{for(const release of [{tag_name:'ChatGPT2.4.18',html_url:'https://example.com'}, {tag_name:'ChatGPT2.4.18',html_url:'https://github.com/kitomisaitichi-design/chatgpt-exporter/releases/tag/ChatGPT2.4.18',prerelease:true}]){const f=fixture({fetch:async()=>Response.json(release)});const result=await f.checker.check();assert.equal(result.available,false);assert.match(result.lastError,/unexpected release/);}});
test('off aborts an automatic request and does not recreate its alarm',async()=>{const f=fixture({fetch:(url,{signal})=>new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(new DOMException('cancelled','AbortError'))))});const task=f.checker.check();await new Promise(r=>setTimeout(r,0));await f.checker.setInterval('off');const result=await task;assert.equal(result.interval,'off');assert.equal(result.nextCheckAt,0);assert.equal(f.alarms.size,0);assert.equal(result.lastError,null);});
