import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs/promises';
import {webcrypto,createHash} from 'node:crypto';
import {newJob,mergeEntry,attachmentError} from '../ChatGPT-Exporter-English-Edge/core.mjs';
import {Engine} from '../ChatGPT-Exporter-English-Edge/engine.mjs';
const scope={user:'fixture',account:'workspace',key:'fixture-key'},id='aaaaaaaa-bbbb-cccc-dddd-000000000001',id2='aaaaaaaa-bbbb-cccc-dddd-000000000002';
const body=cid=>({conversation_id:cid,title:'Fixture',update_time:100,mapping:{a:{message:{author:{role:'user'},content:{parts:['hello']}},children:[]}},current_node:'a'});
const hash=data=>createHash('sha256').update(JSON.stringify(data)).digest('hex');
function harness(overrides={}){let now=1700000000000;const j=newJob(scope,{projects:false,archived:false,attachments:false,passive:false,mode:'balanced'});j.sources=[];const cache=new Map(),requests=[];const io={now:()=>now,sleep:async ms=>{now+=ms;},save:async()=>{},changed:()=>{},cacheGet:async k=>cache.get(k),cachePut:async(k,v)=>cache.set(k,v),hash:async d=>hash(d),write:async()=>{},report:async()=>{},request:async p=>{requests.push(p);return {ok:true,data:body(p.split('/').at(-1))};},...overrides};return {j,cache,requests,e:new Engine(j,io)};}
test('list time newer than detail does not repeatedly refresh the same chat',async()=>{const h=harness();mergeEntry(h.j,{id,update_time:200});await h.e.process(h.j.entries[id]);assert.equal(h.j.entries[id].update_time,200);assert.equal(h.j.entries[id].checkedUpdateTime,200);mergeEntry(h.j,{id,update_time:200,origin:'app conversation list'});assert.equal(h.j.entries[id].status,'saved');mergeEntry(h.j,{id,update_time:201,origin:'app conversation list'});assert.equal(h.j.entries[id].status,'pending');assert.equal(h.requests.length,1);});
test('one failed file yields to other chats and stops after three attempts',async()=>{const order=[];const h=harness({write:async p=>{order.push(p);if(p.includes(id))throw new Error('disk fixture failure');}});mergeEntry(h.j,{id});mergeEntry(h.j,{id:id2});await h.e.run();assert.equal(h.j.entries[id].status,'failed');assert.equal(h.j.entries[id].attempts,3);assert.equal(h.j.entries[id2].status,'saved');assert.ok(order[1].includes(id2));assert.equal(h.requests.filter(p=>p.endsWith(id)).length,1,'failed writes reuse cached bytes');});
test('network status zero is bounded and healthy chats continue',async()=>{const h=harness({request:async p=>p.endsWith(id)?{ok:false,status:0}:{ok:true,data:body(id2)}});mergeEntry(h.j,{id});mergeEntry(h.j,{id:id2});await h.e.run();assert.equal(h.j.entries[id].status,'failed');assert.equal(h.j.entries[id2].status,'saved');});
test('cached changed-body snapshots are handled once',async()=>{const h=harness();mergeEntry(h.j,{id});Object.assign(h.j.entries[id],{status:'saved',contentHash:'old'});h.e.io.sense=async()=>[{changedBodies:[{id,contentHash:'new',previousContentHash:'old'}]}];await h.e.observe();h.j.entries[id].status='saved';await h.e.observe();assert.equal(h.j.entries[id].status,'saved');});
test('105-byte GetDownloadLinkError is rejected; genuine JSON remains valid',()=>{assert.equal(attachmentError('{"status":"error","error_code":"file_not_found","error_type":"GetDownloadLinkError","error_message":null}'),'file_not_found');assert.equal(attachmentError('{"status":"success","content":"personal JSON"}'),null);assert.equal(attachmentError('{"error":"a legitimate field"}'),null);});
async function bridgeFixture(reply){const calls=[];const sandbox={window:{addEventListener:()=>{},fetch:async(url,opts)=>{calls.push(String(url));if(String(url).includes('/api/auth/session'))return Response.json({accessToken:'fixture-token',user:{id:scope.user}});return reply(String(url),opts);}},location:{origin:'https://chatgpt.com',href:'https://chatgpt.com/',pathname:'/'},document:{cookie:'_account=workspace'},crypto:webcrypto,URL,Headers,Request,Response,AbortSignal,Uint8Array,btoa,Date};vm.runInNewContext(await fs.readFile(new URL('../ChatGPT-Exporter-English-Edge/bridge.js',import.meta.url),'utf8'),sandbox);return {rpc:sandbox.window.__englishExporterBridgeV238.rpc,calls};}
test('real bridge refuses HTTP-200 file_not_found payload',async()=>{const f=await bridgeFixture(()=>Response.json({status:'error',error_code:'file_not_found',error_type:'GetDownloadLinkError',error_message:null}));const r=await f.rpc({op:'assetPrepare',scope,candidates:['/backend-api/files/download/file-fixture']});assert.equal(r.ok,false);assert.equal(r.status,404);assert.match(r.error,/file_not_found/);});
test('real bridge bounds circular signed download links',async()=>{const f=await bridgeFixture(u=>Response.json({download_url:u}));const r=await f.rpc({op:'assetPrepare',scope,candidates:['/backend-api/files/download/file-fixture']});assert.equal(r.ok,false);assert.equal(r.status,502);assert.equal(f.calls.length,2);});
test('real bridge still returns genuine document bytes and chunks',async()=>{const f=await bridgeFixture(()=>new Response('actual document',{headers:{'content-type':'text/plain'}}));const r=await f.rpc({op:'assetPrepare',scope,candidates:['/backend-api/files/download/file-fixture']});assert.equal(r.ok,true);const c=await f.rpc({op:'assetChunk',key:r.key,offset:0});assert.equal(atob(c.base64),'actual document');assert.equal(c.done,true);});
