import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import {webcrypto,createHash} from 'node:crypto';
import {newJob,mergeEntry} from '../ChatGPT-Exporter-English-Edge/core.mjs';
import {Engine,YieldAttachments} from '../ChatGPT-Exporter-English-Edge/engine.mjs';
import {ensureWatchSchedule,enterWatching,queueFullScanIfDue,hasObservedWork,recentWatchSources} from '../ChatGPT-Exporter-English-Edge/watch.mjs';
const scope={user:'fixture',account:'workspace',key:'fixture-key'},id='aaaaaaaa-bbbb-cccc-dddd-000000000001',other='aaaaaaaa-bbbb-cccc-dddd-000000000002',start=1700000000000;
const body=(cid,text='hello',time=100)=>({conversation_id:cid,title:'Fixture',update_time:time,current_node:'a',mapping:{a:{message:{author:{role:'user'},content:{parts:[text]}},children:[]}}});
const hash=d=>createHash('sha256').update(JSON.stringify(d)).digest('hex');
function harness(options={},extra={}){let now=start;const job=newJob(scope,{projects:false,archived:false,attachments:false,yieldUser:false,passive:true,...options},now);job.sources=[];ensureWatchSchedule(job,now);const cache=new Map(),requests=[],writes=[];const io={now:()=>now,sleep:async ms=>{now+=ms;},save:async()=>{},changed:()=>{},sense:async()=>[],cacheGet:async k=>cache.get(k),cachePut:async(k,v)=>cache.set(k,v),hash:async d=>hash(d),write:async p=>writes.push(p),report:async()=>{},index:async()=>{},request:async p=>{requests.push(p);return {ok:true,data:p.includes('/conversations?')?{items:[{id:other,title:'remote chat',update_time:200}]}:body(p.split('/').at(-1))};},...extra};return {job,cache,requests,writes,engine:new Engine(job,io),advance:ms=>now+=ms};}
test('watch checks recent metadata without a visible link or app capture',async()=>{const h=harness(),deadline=h.job.schedule.nextScanAt;await h.engine.run();assert.equal(h.job.entries[other].status,'saved');assert.ok(h.requests.some(p=>p.includes('order=updated')));assert.ok(h.requests.some(p=>p.endsWith(other)));assert.equal(h.job.schedule.nextScanAt,deadline);assert.equal(h.job.schedule.lastCheckAt>=start,true);});
test('unrelated exports and watching never slide a full scan deadline',async()=>{const h=harness();h.job.schedule.nextCheckAt=start+300000;mergeEntry(h.job,{id});h.cache.set(scope.key+':'+id,{data:body(id)});const deadline=h.job.schedule.nextScanAt;await h.engine.run();enterWatching(h.job,start+1000);enterWatching(h.job,start+2000);assert.equal(h.job.schedule.nextScanAt,deadline);});
test('due full scan queues during attachment/export work without losing known entries',()=>{const h=harness();mergeEntry(h.job,{id});h.job.schedule.nextScanAt=start-1;assert.equal(queueFullScanIfDue(h.job,start),true);assert.ok(h.job.sources.some(s=>s.key==='active'&&!s.done));assert.ok(h.job.entries[id]);assert.equal(queueFullScanIfDue(h.job,start),false);});
test('a long initial traversal is never discarded by the full scan timer',()=>{const h=harness();h.job.sources=[{key:'active',kind:'list',offset:500,done:false}];h.job.schedule.nextScanAt=start-1;assert.equal(queueFullScanIfDue(h.job,start),false);assert.equal(h.job.sources[0].offset,500);});
test('an interrupted local revision survives stale disk inventory on resume',async()=>{const h=harness({passive:false});mergeEntry(h.job,{id});Object.assign(h.job.entries[id],{status:'pending',refresh:false,contentHash:'latest',previousContentHash:'previous',retryAt:start+1000});await h.engine.reconcileInventory([{id,diskBacked:true,contentHash:'old',previousContentHash:'older'}]);assert.equal(h.job.entries[id].status,'pending');assert.equal(h.job.entries[id].contentHash,'latest');assert.equal(h.job.entries[id].previousContentHash,'previous');assert.equal(h.job.entries[id].retryAt,start+1000);});
test('recent checks rotate through project metadata and include archive/previews',()=>{const h=harness({projects:true,archived:true});h.job.sources=[{kind:'project',key:'project-one',done:true},{kind:'project',key:'project-two',done:true}];const first=recentWatchSources(h.job),second=recentWatchSources(h.job);assert.ok(first.some(s=>s.archived));assert.ok(first.some(s=>s.kind==='projects'));assert.equal(first.at(-1).key,'project-one');assert.equal(second.at(-1).key,'project-two');});
test('server cooldown defers autonomous metadata polling without requests',async()=>{const h=harness();h.job.pace.until=start+600000;await h.engine.run();assert.equal(h.requests.length,0);assert.equal(h.job.schedule.checkState,'waiting');assert.equal(h.job.schedule.checkWaitUntil,start+600000);});
test('completed reply forces one fresh read despite unchanged server timestamp',async()=>{const revision='document:10',h=harness({}, {sense:async()=>[{changedChats:[{id,revision,at:start+1}]}],request:async p=>{h.requests.push(p);return {ok:true,data:body(id,'updated reply')};}});h.job.schedule.nextCheckAt=start+300000;mergeEntry(h.job,{id,update_time:100});Object.assign(h.job.entries[id],{status:'saved',contentHash:hash(body(id)),checkedUpdateTime:100});h.cache.set(scope.key+':'+id,{data:body(id),at:start-100,passive:true});await h.engine.run();assert.equal(h.requests.length,1);assert.equal(h.job.entries[id].revisionCount,1);assert.equal(h.job.entries[id].nativeWriteRevision,revision);assert.equal(hasObservedWork(h.job,[{changedChats:[{id,revision,at:start+1}]}]),false);});
test('fresh captured body can be saved locally during a server cooldown',async()=>{const h=harness({}, {sense:async()=>[{changedBodies:[{id,contentHash:hash(body(id,'new')),previousContentHash:hash(body(id))}]}]});h.job.pace.until=start+600000;mergeEntry(h.job,{id,update_time:100});Object.assign(h.job.entries[id],{status:'saved',contentHash:hash(body(id)),checkedUpdateTime:100});h.cache.set(scope.key+':'+id,{data:body(id,'new'),at:start,passive:true});await h.engine.run();assert.equal(h.requests.length,0);assert.equal(h.job.entries[id].status,'saved');assert.equal(h.job.entries[id].revisionCount,1);assert.equal(h.writes.length,2);assert.equal(h.job.pace.until,start+600000);});
test('attachment work yields before a network wait when a chat appears',async()=>{const h=harness({attachments:true,passive:false},{sense:async()=>[{hints:[{id:other}]}],attachments:async(e,d,b,before)=>{await assert.rejects(before(),YieldAttachments);return [{name:'x.txt',status:'deferred',yielded:true}];}});mergeEntry(h.job,{id});Object.assign(h.job.entries[id],{status:'saved'});h.cache.set(scope.key+':'+id,{data:{...body(id),mapping:{a:{message:{metadata:{attachments:[{id:'file-test123',name:'x.txt',size:5}]}}}}}});await h.engine.processAttachments(h.job.entries[id]);assert.equal(h.job.entries[other].status,'pending');assert.equal(h.requests.length,0);assert.equal(h.job.entries[id].attachmentRetryAt,start+60000);});
test('bridge emits a completed streamed reply once, including a new conversation ID',async()=>{const encoder=new TextEncoder(),stream=new ReadableStream({start(c){c.enqueue(encoder.encode('data: {"conversation_id":"'+id+'","message":{"content":"reply"}}\n\n'));c.close();}});const sandbox={window:{addEventListener:()=>{},fetch:async url=>String(url).includes('/api/auth/session')?Response.json({accessToken:'token',user:{id:scope.user}}):new Response(stream,{headers:{'content-type':'text/event-stream'}})},location:{origin:'https://chatgpt.com',href:'https://chatgpt.com/',pathname:'/'},document:{cookie:'_account=workspace',readyState:'complete',title:'Fixture',querySelector:()=>null,querySelectorAll:()=>[]},crypto:webcrypto,URL,Headers,Request,Response,AbortSignal,Uint8Array,btoa,Date,TextDecoder};vm.runInNewContext(await fs.readFile(new URL('../ChatGPT-Exporter-English-Edge/bridge.js',import.meta.url),'utf8'),sandbox);const rpc=sandbox.window.__englishExporterBridgeV238.rpc;await rpc({op:'context'});await sandbox.window.fetch('https://chatgpt.com/backend-api/f/conversation',{method:'POST',body:'{"conversation_id":null}'});let sense;for(let n=0;n<20;n++){await new Promise(setImmediate);sense=await rpc({op:'sense',scope});if(sense.changedChats?.length)break;}assert.equal(sense.changedChats.length,1);assert.equal(sense.changedChats[0].id,id);assert.equal(sense.activeStreams,0);assert.equal((await rpc({op:'sense',scope})).changedChats[0].revision,sense.changedChats[0].revision);});

