import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
import {newJob} from '../ChatGPT-Exporter-English-Edge/core.mjs';
import {libraryState,normalizeLibraryItem,mergeLibraryItem,queueLibraryScan,libraryWork,libraryIndex,processLibrary} from '../ChatGPT-Exporter-English-Edge/library.mjs';
import {CatalogWriter} from '../ChatGPT-Exporter-English-Edge/catalog-writer.mjs';
import {appendEvent,filterEvents} from '../ChatGPT-Exporter-English-Edge/logs.mjs';
import {Engine} from '../ChatGPT-Exporter-English-Edge/engine.mjs';
const scope={user:'fixture',account:'workspace',key:'fixture-key'};
test('quiet checks back off to thirty minutes and new activity restores five minutes',async()=>{let clock=1700000000000,active=false;const j=newJob(scope,{passive:true,archived:false,projects:false,library:false,yieldUser:false},clock);j.sources=[];const deadline=j.schedule.nextScanAt,engine=new Engine(j,{now:()=>clock,sleep:async ms=>clock+=ms,save:async()=>{},sense:async()=>[],index:async()=>{},request:async()=>({ok:true,data:{items:active?[{id:'new-chat-fixture',title:'New chat',update_time:100}]:[]}})});for(let i=0;i<4;i++){await engine.checkRecentChats();clock+=j.schedule.effectiveRecentIntervalMs;}assert.equal(j.schedule.effectiveRecentIntervalMs,1800000);active=true;await engine.checkRecentChats();assert.equal(j.schedule.effectiveRecentIntervalMs,300000);assert.equal(j.schedule.quietChecks,0);assert.equal(j.schedule.nextScanAt,deadline);});
test('offline network work waits for connectivity without losing local progress',async()=>{let clock=1700000000000;const start=clock,j=newJob(scope,{passive:false,library:false,yieldUser:false},clock);j.sources=[];j.entries['saved-fixture']={id:'saved-fixture',status:'saved',path:'json/saved.json'};let offlineSeen=false;const engine=new Engine(j,{now:()=>clock,sleep:async ms=>{clock+=ms;},save:async()=>{},sense:async()=>[],online:()=>clock>=start+30000,changed:()=>{if(j.awareness?.state==='offline')offlineSeen=true;}});await engine.paceRequest('discovery');assert.ok(clock>=start+30000);assert.equal(offlineSeen,true);assert.equal(j.entries['saved-fixture'].status,'saved');assert.equal(j.entries['saved-fixture'].path,'json/saved.json');});
test('a missing saved Library copy is requeued and repaired during resume',async()=>{const j=newJob(scope,{passive:false,attachments:false,library:true,projects:false,archived:false});j.sources=[];const s=libraryState(j);s.nextScanAt=Date.now()+1000000;mergeLibraryItem(s,normalizeLibraryItem({file_id:'file-missing',name:'missing.txt',size:3}));Object.assign(s.entries['file-missing'],{status:'saved',path:'attachments/missing.txt'});let checks=0,downloads=0;const engine=new Engine(j,{save:async()=>{},sense:async()=>[],inventory:async()=>[],report:async()=>{},libraryList:async()=>{throw Error('No discovery request expected');},libraryVerify:async()=>++checks>1,libraryDownload:async()=>{downloads++;return {status:'saved',path:'attachments/repaired.txt',size:3};}});await engine.run();assert.equal(downloads,1);assert.equal(s.entries['file-missing'].status,'saved');assert.equal(s.entries['file-missing'].path,'attachments/repaired.txt');});
function harness(list){let clock=Date.now();const job=newJob(scope,{library:true});const calls=[],engine={job,now:()=>clock,save:async()=>{},paceRequest:async()=>{},event:()=>{},io:{libraryList:async s=>{calls.push({...s});return list(s);},report:async()=>{}}};queueLibraryScan(job,clock,true);return {job,engine,calls,advance:n=>clock+=n};}
test('sparse native observations preserve known metadata and saved bytes',()=>{const s=libraryState(newJob(scope));mergeLibraryItem(s,normalizeLibraryItem({file_id:'file-one',name:'report.pdf',size:8,updated_at:5}));Object.assign(s.entries['file-one'],{status:'saved',path:'attachments/x'});mergeLibraryItem(s,normalizeLibraryItem({file_id:'file-one'}));assert.equal(s.entries['file-one'].name,'report.pdf');assert.equal(s.entries['file-one'].size,8);assert.equal(s.entries['file-one'].status,'saved');});
test('full pages without pagination metadata are verified with a following page',async()=>{const h=harness(s=>({ok:true,data:{items:s.offset?[]:Array.from({length:100},(_,i)=>({file_id:'file-'+i,size:10000000}))}}));await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));assert.equal(h.job.library.sources[0].done,false);await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));assert.equal(h.calls[1].offset,100);assert.equal(libraryIndex(h.job).coverage_complete,true);});
test('folder discovery resumes through nested directories without duplicating files',async()=>{const h=harness(s=>({ok:true,data:{items:s.parent?[{file_id:'file-child',size:2}]:[{type:'directory',id:'folder-one',name:'Folder'},{file_id:'file-root',size:10000000}]}}));await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));assert.equal(h.calls[1].parent,'folder-one');assert.equal(Object.keys(h.job.library.entries).length,2);assert.equal(libraryIndex(h.job).coverage_complete,true);});
test('repeated cursor reports incomplete coverage and has bounded retries',async()=>{const h=harness(()=>({ok:true,data:{items:[{file_id:'file-repeat',size:10000000}],next_cursor:'same'}}));await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));for(let i=0;i<3;i++){await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));h.advance(1000000);}assert.equal(h.job.library.sources[0].failures,3);assert.equal(libraryIndex(h.job).coverage_complete,false);assert.equal(libraryWork(h.job,h.engine.now()),null);});
test('a transient list failure resumes the same page and consumes native limit once',async()=>{let n=0;const h=harness(()=>++n===1?{ok:false,status:429,observedAt:55,error:'cooldown'}:{ok:true,data:{items:[{file_id:'file-retry',size:10000000}]}});await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));assert.equal(h.job.lastLimitSeen,55);assert.equal(libraryWork(h.job,h.engine.now()),null);h.advance(500000);await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));assert.equal(h.calls[1].offset,0);assert.equal(libraryIndex(h.job).coverage_complete,true);});
test('manual records include stable expected paths for viewer import',()=>{const j=newJob(scope),s=libraryState(j);mergeLibraryItem(s,normalizeLibraryItem({file_id:'file-large',name:'report.pdf',size:10000000}));const f=libraryIndex(j).entries[0];assert.equal(f.path,null);assert.equal(f.expected_path,'attachments/library/file-large/report.pdf');});
test('catalog writer skips unchanged snapshots, batches changes, and flushes on stop',async()=>{let now=0;const writes=[],j=newJob(scope),writer=new CatalogWriter(async p=>writes.push(p),()=>now),root={};await writer.report(j,root);await writer.report(j,root);assert.equal(writes.length,4);mergeLibraryItem(libraryState(j),normalizeLibraryItem({file_id:'file-new',size:1}));assert.equal(await writer.report(j,root),false);assert.equal(await writer.report(j,root,true),true);assert.equal(writes.length,8);now=3000;assert.equal(await writer.report(j,root),false);await writer.report(j,{});assert.equal(writes.length,12);});
test('clearing the log view still permits a later coalesced notice',()=>{const j=newJob(scope);appendEvent(j,'Repeated notice',10);appendEvent(j,'Repeated notice',20);assert.equal(filterEvents(j.events,{since:10}).length,1);assert.equal(filterEvents(j.events,{since:20}).length,0);});
async function bridge(fetch){const sandbox={window:{addEventListener:()=>{},fetch},location:{origin:'https://chatgpt.com',href:'https://chatgpt.com/',pathname:'/'},document:{cookie:'_account=workspace',readyState:'complete',title:'Fixture',querySelector:()=>null,querySelectorAll:()=>[]},crypto:webcrypto,URL,Headers,Request,Response,AbortSignal,Uint8Array,btoa,Date,TextDecoder};vm.runInNewContext(await fs.readFile(new URL('../ChatGPT-Exporter-English-Edge/bridge.js',import.meta.url),'utf8'),sandbox);const rpc=sandbox.window.__englishExporterBridgeV240.rpc;await rpc({op:'context'});return rpc;}
test('oversize Content-Length cancels the body before reading any chunks',async()=>{let cancelled=false,read=0;const rpc=await bridge(async url=>String(url).includes('/api/auth/session')?Response.json({accessToken:'token',user:{id:scope.user}}):new Response(new ReadableStream({pull(){read++;},cancel(){cancelled=true;}}),{headers:{'content-length':'10000000'}}));const r=await rpc({op:'assetPrepare',scope,candidates:['/backend-api/estuary/content?id=file-big&sig=test'],maxBytes:9999999});assert.equal(r.status,413);assert.equal(cancelled,true);assert.ok(read<=1);});
test('unknown-size streams crossing the limit are cancelled and never cached',async()=>{let cancelled=false;const rpc=await bridge(async url=>String(url).includes('/api/auth/session')?Response.json({accessToken:'token',user:{id:scope.user}}):new Response(new ReadableStream({pull(c){c.enqueue(new Uint8Array(1000000));},cancel(){cancelled=true;}}),{headers:{'content-type':'application/octet-stream'}}));const r=await rpc({op:'assetPrepare',scope,candidates:['/backend-api/estuary/content?id=file-big&sig=test'],maxBytes:9999999});assert.equal(r.status,413);assert.equal(cancelled,true);assert.equal(r.key,undefined);});
