import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {scanLocalFileCopies,iterateLocalCopyCandidates,verifyLocalCopy} from '../ChatGPT-Exporter-English-Edge/local-files.mjs';
import {LocalIndexSession} from '../ChatGPT-Exporter-English-Edge/local-index.mjs';
import {ContentStore,contentHash} from '../ChatGPT-Exporter-English-Edge/file-intelligence.mjs';
import {createFileLookup,observeFileSource,rememberFileResult,invalidateFileLookup} from '../ChatGPT-Exporter-English-Edge/file-links.mjs';
import {newJob} from '../ChatGPT-Exporter-English-Edge/core.mjs';
import {Engine,Paused} from '../ChatGPT-Exporter-English-Edge/engine.mjs';
import {libraryState,processLibrary} from '../ChatGPT-Exporter-English-Edge/library.mjs';
const scope={key:'incremental-fixture',user:'fixture'},sha=b=>createHash('sha256').update(b).digest('hex');
class Dir{
  constructor(name,items={}){this.name=name;this.kind='directory';this.items=items;}
  async *entries(){yield* Object.entries(this.items);}async isSameEntry(h){return h===this;}
  async getFileHandle(n){if(this.items[n]?.kind==='file')return this.items[n];throw Object.assign(Error('Missing'),{name:'NotFoundError'});}
  async getDirectoryHandle(n){if(this.items[n]?.kind==='directory')return this.items[n];throw Object.assign(Error('Missing'),{name:'NotFoundError'});}
}
function file(name,body,counters={opens:0},mtime=1){return {kind:'file',name,body,mtime,async isSameEntry(h){return h===this;},async getFile(){counters.opens++;const blob=new Blob([this.body]);Object.defineProperties(blob,{name:{value:name},lastModified:{value:this.mtime}});return blob;}};}
async function linear(n){const counts={opens:0,hashes:0},items={},hashes=[];for(let i=0;i<n;i++){const bytes=Buffer.alloc(1000,i);items[i+'.bin']=file(i+'.bin',bytes,counts);hashes.push(sha(bytes));}const inventory=await scanLocalFileCopies([{handle:new Dir('Copies',items),source:'library'}],scope.key);counts.opens=0;const hash=async b=>{counts.hashes++;return sha(Buffer.from(await b.arrayBuffer()));};for(const expected of hashes.reverse()){let matched=false;for(const c of iterateLocalCopyCandidates(inventory,{size:1000,remoteSha256:expected})){if(await verifyLocalCopy(c,{size:1000,remoteSha256:expected},inventory,hash)){matched=true;break;}}assert.ok(matched);}return counts;}
test('same-size searches classify once and have linear candidate opens in reverse order',async()=>{const a=await linear(100),b=await linear(200);assert.equal(a.hashes,100);assert.equal(b.hashes,200);assert.ok(a.opens<=200);assert.ok(b.opens<=400);assert.ok(b.opens/a.opens<2.05);console.log('Linear lookup evidence',JSON.stringify({files100:a,files200:b}));});
test('unchanged session fingerprints survive rescan; changed metadata is rehashed; reopened hints are untrusted',async()=>{
 const h=file('x.bin','hello'),root=new Dir('Files',{'x.bin':h}),roots=[{handle:root,source:'library'}];let hashes=0;const hash=async b=>{hashes++;return sha(Buffer.from(await b.arrayBuffer()));};const asset={size:5,remoteSha256:sha('hello')};let inv=await scanLocalFileCopies(roots,scope.key);assert.ok(await verifyLocalCopy([...iterateLocalCopyCandidates(inv,asset)][0],asset,inv,hash));inv=await scanLocalFileCopies(roots,scope.key,{priorIndex:inv});assert.ok(await verifyLocalCopy([...iterateLocalCopyCandidates(inv,asset)][0],asset,inv,hash));assert.equal(hashes,1);
 const reopened={records:new Map([...inv.records].map(([k,c])=>[k,{...c,verified:false}]))};inv=await scanLocalFileCopies(roots,scope.key,{priorIndex:reopened});assert.ok(await verifyLocalCopy([...iterateLocalCopyCandidates(inv,asset)][0],asset,inv,hash));assert.equal(hashes,2);h.body='world';h.mtime++;inv=await scanLocalFileCopies(roots,scope.key,{priorIndex:inv});assert.equal(await verifyLocalCopy([...iterateLocalCopyCandidates(inv,asset)][0],asset,inv,hash),null);assert.equal(hashes,3);
});
test('corruption never changes the native ID association into a new trusted hash',async()=>{const h=file('x.bin','world'),root=new Dir('Files',{'x.bin':h,'library-index.json':file('library-index.json',JSON.stringify({scope_key:scope.key,entries:[{id:'file_native',path:'x.bin',sha256:sha('hello')}]}))});const inv=await scanLocalFileCopies([{handle:root,source:'library'}],scope.key),asset={id:'file_native',size:5};const candidates=[...iterateLocalCopyCandidates(inv,asset)];assert.equal(await verifyLocalCopy(candidates[0],asset,inv,contentHash),null);assert.equal([...iterateLocalCopyCandidates(inv,asset)].length,0);});
test('local index shares an in-flight scan and increments without rescanning after writes',async()=>{let scans=0;const batches=[],session=new LocalIndexSession({load:async()=>null,save:async(s,r)=>batches.push(r),scan:async(...args)=>{scans++;await new Promise(r=>setTimeout(r,2));return scanLocalFileCopies(...args);}}),roots=[{handle:new Dir('Files',{'a.bin':file('a.bin','a')}),source:'library'}];const [a,b]=await Promise.all([session.build(roots,scope.key),session.build(roots,scope.key)]);assert.equal(a,b);for(let i=0;i<300;i++)session.register({source:'backup',path:i+'.bin',name:i+'.bin',handle:file(i+'.bin','x'),size:1,lastModified:1,hash:sha('x'),verified:true});assert.equal(await session.build(roots,scope.key),a);await session.flush();assert.equal(scans,1);assert.equal(a.records.size,301);assert.ok(batches.every(b=>b.length<=250));assert.ok(batches.flat().every(c=>!('verified' in c)));session.remove('backup','1.bin');await session.flush();assert.ok(batches.flat().some(c=>c.deleted));await session.reset();});
test('cancelled generation cannot publish late scan results or poison new folder selection',async()=>{let release;const gate=new Promise(r=>release=r),session=new LocalIndexSession({load:async()=>null,save:async()=>{},scan:async(roots,key,options)=>{await gate;await options.checkpoint();return scanLocalFileCopies(roots,key,options);}});const building=session.build([],scope.key);await Promise.resolve();await session.reset();release();await assert.rejects(building,{name:'Paused'});assert.equal(session.index,null);});
test('failed index checkpoint retains dirty rows for retry and scopes remain separate',async()=>{let fail=true;const rows=[],session=new LocalIndexSession({load:async()=>null,save:async(s,r)=>{if(fail)throw Error('disk full');rows.push({s,r});}});session.scope='old';session.changed({key:'a',path:'a',hash:sha('a')});await assert.rejects(session.flush(),/disk full/);assert.equal(session.dirty.size,1);fail=false;await session.reset();await session.build([],'new');assert.equal(rows[0].s,'old');assert.equal(session.scope,'new');await session.reset();});
test('overlapping roots are scanned once and permission loss is visible',async()=>{const child=new Dir('nested',{'x.bin':file('x.bin','x')}),parent=new Dir('parent',{nested:child});const inv=await scanLocalFileCopies([{handle:child,source:'first'},{handle:parent,source:'parent'}],scope.key);assert.equal(inv.eligible,1);child.entries=async function*(){throw Object.assign(Error('Permission lost'),{name:'NotAllowedError'});};await assert.rejects(scanLocalFileCopies([{handle:child,source:'first'}],scope.key),{name:'NotAllowedError'});});
function storeFixture(){const job=newJob(scope),disk=new Map(),removed=[];libraryState(job);const store=new ContentStore(()=>job,{read:async p=>{if(!disk.has(p))throw Object.assign(Error('Missing'),{name:'NotFoundError'});return disk.get(p);},write:async(p,b)=>disk.set(p,b),remove:async p=>{removed.push(p);disk.delete(p);},commit:async()=>{}});return {job,disk,store,removed};}
test('shared lookup updates native ID/hash/path buckets without rebuilding per save',async()=>{const h=storeFixture(),lookup=createFileLookup(h.job);for(let i=0;i<100;i++){const f={id:'file_'+i,name:i+'.bin',size:5,status:'pending'};h.job.library.entries[f.id]=f;observeFileSource(h.job,f,'library');rememberFileResult(h.job,f,{status:'saved',path:'attachments/x.bin',sha256:sha('hello'),size:5});assert.equal(createFileLookup(h.job),lookup);}assert.equal(lookup.byPath.get('attachments/x.bin').size,200);assert.equal(lookup.byHash.get(sha('hello')).size,200);const f=h.job.library.entries.file_0;rememberFileResult(h.job,f,{status:'saved',path:'attachments/y.bin',sha256:sha('world'),size:5});assert.ok(!lookup.byHash.get(sha('hello')).has(f));assert.ok(lookup.byHash.get(sha('world')).has(f));assert.ok([...lookup.byHash.get(sha('hello'))].some(f=>f.historical));});
test('automatic maintenance links identical bytes but keeps physical copies and versions',async()=>{const h=storeFixture();for(const [id,text] of [['a','hello'],['b','hello'],['c','world']]){const path='attachments/'+id+'.bin';h.disk.set(path,new Blob([text]));h.job.library.entries[id]={id,name:id+'.bin',status:'saved',path,size:5};}for(let i=0;i<3;i++)assert.equal(await h.store.maintenanceTurn(),true);assert.equal(await h.store.maintenanceTurn(),false);assert.equal(h.job.library.entries.a.path,h.job.library.entries.b.path);assert.notEqual(h.job.library.entries.c.path,h.job.library.entries.a.path);assert.equal(h.disk.size,3);assert.equal(h.removed.length,0);assert.equal(h.job.library.deduplication.pending.length,1);assert.equal((await h.store.deduplicate()).removed,1);assert.equal(h.disk.size,2);});
test('Hold/Stop after hashing prevents late automatic linking and keeps resumable copies',async()=>{const h=storeFixture();for(const id of ['a','b']){const path='attachments/'+id+'.bin';h.disk.set(path,new Blob(['hello']));h.job.library.entries[id]={id,status:'saved',path,size:5};}await h.store.maintenanceTurn();let calls=0;h.store.checkpoint=async()=>{if(++calls===2)throw new Paused('Stopped');};await assert.rejects(h.store.maintenanceTurn(),{name:'Paused'});assert.equal(h.job.library.entries.b.path,'attachments/b.bin');assert.equal(h.disk.size,2);assert.equal(h.removed.length,0);h.store.checkpoint=async()=>{};assert.equal(await h.store.maintenanceTurn(),true);assert.equal(h.job.library.entries.b.path,h.job.library.entries.a.path);assert.equal(h.disk.size,2);});
test('permission and unexpected inspection errors do not become silent misses',async()=>{const h=storeFixture(),hash=sha('hello');h.job.library.entries.a={id:'a',status:'saved',path:'attachments/a',sha256:hash};h.store.read=async()=>{throw Object.assign(Error('Denied'),{name:'NotAllowedError'});};await assert.rejects(h.store.find(hash),{name:'NotAllowedError'});h.store.read=async()=>{throw Error('Unexpected filesystem failure');};await assert.rejects(h.store.find(hash),/Unexpected/);});
test('deferred local search never increments the two-failure budget',async()=>{const h=storeFixture(),f={id:'a',name:'a',status:'pending',attempts:1,size:5};h.job.library.entries.a=f;const engine={job:h.job,now:()=>1000,save:async()=>{},event:()=>{},io:{libraryDownload:async()=>({localPending:true,status:'deferred'}),report:async()=>{}}};await processLibrary(engine,{file:f});assert.equal(f.attempts,1);assert.equal(!!f.parked,false);assert.equal(f.retryAt,1250);});
test('engine wait permits bounded maintenance but Hold and Stop suspend it',async()=>{const job=newJob(scope);let now=0,turns=0;const e=new Engine(job,{now:()=>now,save:async()=>{},maintenance:async()=>{turns++;},sleep:async ms=>{now+=ms;if(e.held)e.stopped=true;}});await e.wait(2100,'cooldown');assert.equal(turns,3);e.held=true;await assert.rejects(e.wait(3000,'held'),{name:'Paused'});assert.equal(turns,3);});
test('completed misses never revisit classified size or name buckets',async()=>{const root=new Dir('Files',{'same.bin':file('same.bin','hello')}),inv=await scanLocalFileCopies([{handle:root,source:'library'}],scope.key);for(const c of inv.records.values())await verifyLocalCopy(c,{remoteSha256:sha('world'),size:5},inv,contentHash);inv.bySize.get=()=>{throw Error('Classified bucket revisited');};assert.equal([...iterateLocalCopyCandidates(inv,{name:'same.bin',size:5,remoteSha256:sha('never')})].length,0);assert.equal([...iterateLocalCopyCandidates(inv,{name:'same.bin',remoteSha256:sha('never')})].length,0);});
test('hash work is serialized and the same immutable blob is read once',async()=>{let active=0,maximum=0,reads=0;class CountedBlob extends Blob{async arrayBuffer(){reads++;active++;maximum=Math.max(maximum,active);await new Promise(r=>setTimeout(r,1));const data=await super.arrayBuffer();active--;return data;}}const blobs=Array.from({length:10},(_,i)=>new CountedBlob([String(i)]));await Promise.all([...blobs,...blobs].map(contentHash));assert.equal(maximum,1);assert.equal(reads,10);});
test('fast-path build retries a failed checkpoint without rescanning',async()=>{let saves=0,scans=0;const session=new LocalIndexSession({load:async()=>null,save:async()=>{if(++saves===1)throw Error('disk full');},scan:async(...args)=>{scans++;return scanLocalFileCopies(...args);}}),roots=[{source:'library',handle:new Dir('Files',{'a.bin':file('a.bin','a')})}];await assert.rejects(session.build(roots,scope.key),/disk full/);await session.build(roots,scope.key);assert.equal(saves,2);assert.equal(scans,1);await session.reset();});
test('cancellation checkpoints run for empty directory trees',async()=>{const root=new Dir('Files',{empty:new Dir('empty',{deeper:new Dir('deeper')})});let calls=0;await assert.rejects(scanLocalFileCopies([{source:'library',handle:root}],scope.key,{checkpoint:async()=>{if(++calls===2)throw new Paused('Cancelled');}}),{name:'Paused'});assert.equal(calls,2);});
test('late dirty callbacks from an old folder cannot persist into the next scope',async()=>{const saved=[],session=new LocalIndexSession({load:async()=>null,save:async(s,rows)=>saved.push({s,rows})}),old=await session.build([{source:'library',handle:new Dir('Old',{'a.bin':file('a.bin','a')})}],'old');await session.reset();await session.build([],'new');old.onDirty({key:'late',path:'a.bin',hash:sha('a')});await session.flush();assert.ok(!saved.some(batch=>batch.s==='new'));await session.reset();});
