import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
import {newJob} from '../ChatGPT-Exporter-English-Edge/core.mjs';
import {libraryState,libraryPage,normalizeLibraryItem,mergeLibraryItem,libraryCandidates,queueLibraryScan,libraryWork,processLibrary,retryLibraryFile,libraryIndex} from '../ChatGPT-Exporter-English-Edge/library.mjs';
import {selectLibraryFiles} from '../ChatGPT-Exporter-English-Edge/library-ui.mjs';
import {Engine} from '../ChatGPT-Exporter-English-Edge/engine.mjs';
const scope={key:'test',user:'fixture',account:'workspace'};
function harness(download=async()=>({status:'unavailable',httpStatus:404,error:'file_not_found'})){
 let clock=1700000000000,saves=0;const job=newJob(scope,{library:true}),state=libraryState(job,clock);state.sources=[];state.nextScanAt=clock+10000000;mergeLibraryItem(state,normalizeLibraryItem({file_id:'file_00000001',id:'libfile_fixture',name:'example.txt',size:3}));
 const engine={job,now:()=>clock,save:async()=>{saves++;},event:()=>{},paceRequest:async()=>{},io:{libraryDownload:download,report:async()=>{}}};return {job,state,engine,advance:()=>clock+=180000,saves:()=>saves};
}
test('real native cursor is followed, including an explicit null end marker',()=>{assert.equal(libraryPage({items:[],cursor:'opaque:next'}).cursor,'opaque:next');assert.equal(libraryPage({items:[],cursor:null}).cursorProvided,true);});
test('native source chat and directory IDs survive both Library shapes',()=>{for(const raw of [{id:'libfile_one',file_id:'file_one',file_name:'example.txt',directory_id:'folder_one',origination_thread_id:'fixture-chat',file_size_bytes:3},{kind:'file',id:'libfile_one',file_id:'file_one',name:'example.txt',parent_directory_id:'folder_one',origination_thread_id:'fixture-chat',file_size_bytes:3}]){const f=normalizeLibraryItem(raw);assert.equal(f.fileId,'file_one');assert.equal(f.parent,'folder_one');assert.deepEqual(f.conversationIds,['fixture-chat']);assert.equal(libraryCandidates(f)[0],'/backend-api/files/download/file_one');assert.ok(libraryCandidates(f).some(x=>x.includes('conversation_id=fixture-chat')));assert.ok(libraryCandidates(f).every(x=>!x.includes('inline=false')));}});
test('mounted folders and an unknown node do not block later files, cursor pages or owned folders',async()=>{const h=harness();queueLibraryScan(h.job,h.engine.now(),true);h.engine.io.libraryList=async source=>({ok:true,data:source.parent?{items:[{file_id:'file_child',size:10000000}],cursor:null}:source.cursor?{items:[{file_id:'file_next',size:10000000}],cursor:null}:{items:[{kind:'directory',access_kind:'mounted',id:'external:google_drive/root',name:'Connected folder'},{kind:'directory',id:'owned-folder'}, {unsupported:true},{file_id:'file_after_unknown',size:10000000}],cursor:'opaque:next'}});for(let i=0;i<3;i++)await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));assert.ok(h.state.entries.file_next);assert.ok(h.state.entries.file_child);assert.ok(h.state.entries.file_after_unknown);assert.equal(h.state.sources.length,2);assert.equal(h.state.sources.every(x=>x.done),true);assert.equal(libraryIndex(h.job).coverage_complete,false);assert.equal(h.state.sources[0].unsupported,1);});
test('mounted folder IDs are cataloged for manual access without incomplete owned coverage',async()=>{const h=harness();queueLibraryScan(h.job,h.engine.now(),true);h.engine.io.libraryList=async()=>({ok:true,data:{items:[{kind:'directory',access_kind:'mounted',id:'external:google_drive/root'}],cursor:null}});await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));assert.equal(h.state.sources.length,1);assert.equal(libraryIndex(h.job).coverage_complete,true);assert.equal(Object.values(h.state.directories)[0].external,true);});
test('HTTP unavailable failures park after two attempts and persist through serialization and rescan',async()=>{const h=harness(),f=h.state.entries.file_00000001;await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));assert.equal(f.attempts,1);h.advance();await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));assert.equal(f.attempts,2);assert.equal(f.parked,true);const loaded=JSON.parse(JSON.stringify(h.job));mergeLibraryItem(loaded.library,normalizeLibraryItem({file_id:f.id,name:'renamed.txt',size:4,updated_at:1900000000}));assert.equal(loaded.library.entries[f.id].parked,true);assert.equal(loaded.library.entries[f.id].attempts,2);assert.equal(libraryWork(loaded,h.engine.now()),null);assert.equal(libraryIndex(loaded).entries[0].parked,true);assert.ok(h.saves()>=4);});
test('the first failure is also remembered when native metadata changes',async()=>{const h=harness(),f=h.state.entries.file_00000001;await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));mergeLibraryItem(h.state,normalizeLibraryItem({file_id:f.id,size:4,updated_at:1900000000}));assert.equal(h.state.entries[f.id].attempts,1);assert.equal(h.state.entries[f.id].retryAt,f.retryAt);h.advance();await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));assert.equal(h.state.entries[f.id].parked,true);});
test('exceptions and permission failures share the same two-attempt budget',async()=>{let n=0;const h=harness(async()=>{if(++n===1)throw Error('transfer interrupted');return {status:'permission-unavailable',httpStatus:403,error:'access denied'};});await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));h.advance();await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));const f=h.state.entries.file_00000001;assert.equal(f.attempts,2);assert.equal(f.parked,true);assert.equal(f.lastFailureStatus,403);assert.equal(f.failureHistory.length,2);});
test('server cooldowns and user stops never spend a file failure attempt',async()=>{let mode='cooldown',limits=0;const h=harness(async()=>{if(mode==='stop'){const e=Error('Stopped');e.name='Paused';throw e;}return {status:'deferred',httpStatus:429,retryAfter:'30'};});h.engine.io.libraryLimit=()=>limits++;await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));assert.equal(h.state.entries.file_00000001.attempts,undefined);assert.equal(limits,1);h.advance();mode='stop';await assert.rejects(processLibrary(h.engine,libraryWork(h.job,h.engine.now())),/Stopped/);assert.equal(h.state.entries.file_00000001.attempts,undefined);});
test('explicit retry releases only the selected file and starts a new bounded attempt cycle',async()=>{const h=harness(),f=h.state.entries.file_00000001;for(let i=0;i<2;i++){await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));h.advance();}h.state.entries.other={...f,id:'file_other'};assert.equal(retryLibraryFile(f,h.engine.now()),true);assert.equal(f.attempts,0);assert.equal(f.parked,false);assert.equal(h.state.entries.other.parked,true);assert.equal(libraryWork(h.job,h.engine.now()).file.id,f.id);assert.equal(retryLibraryFile({status:'manual'}),false);});
test('native observations during pacing cannot discard a completed file transfer or its failed attempt',async()=>{for(const result of [{status:'saved',size:3,path:'attachments/library/file_00000001/example.txt',sha256:'fixture-hash'},{status:'unavailable',httpStatus:404,error:'file_not_found'}]){const h=harness(async(f,beforeRequest)=>{await beforeRequest();return result;}),f=h.state.entries.file_00000001;h.engine.paceRequest=async()=>{mergeLibraryItem(h.state,normalizeLibraryItem({file_id:f.id,name:'example.txt',size:3}));};await processLibrary(h.engine,libraryWork(h.job,h.engine.now()));assert.equal(h.state.entries[f.id],f);assert.equal(f.status,result.status==='saved'?'saved':'deferred');assert.equal(result.status==='saved'?f.path:f.attempts,result.status==='saved'?result.path:1);}});
test('an autonomous run waits for the second file attempt and then finishes with the file parked',async()=>{let clock=1700000000000,downloads=0;const job=newJob(scope,{passive:false,attachments:false,library:true,projects:false,archived:false,yieldUser:false});job.sources=[];const s=libraryState(job,clock);s.nextScanAt=clock+10000000;mergeLibraryItem(s,normalizeLibraryItem({file_id:'file_wait',name:'example.txt',size:3}));const engine=new Engine(job,{now:()=>clock,sleep:async ms=>{clock+=ms;},save:async()=>{},sense:async()=>[],inventory:async()=>[],report:async()=>{},libraryList:async()=>{throw Error('No discovery expected');},libraryDownload:async(f,before)=>{await before();downloads++;return {status:'unavailable',httpStatus:404,error:'file_not_found'};}});await engine.run();assert.equal(downloads,2);assert.equal(s.entries.file_wait.parked,true);assert.equal(job.status,'complete');assert.match(job.message,/1 parked/);});
test('250 Library files are reachable by page, last page, all, sorting and filters',()=>{const files=Array.from({length:250},(_,i)=>({id:'file_'+i,name:String(i).padStart(3,'0')+'.txt',size:i,status:i%2?'saved':'manual',parked:false}));assert.equal(selectLibraryFiles(files,{sort:'name',page:1}).files[0].name,'050.txt');assert.equal(selectLibraryFiles(files,{sort:'name',page:999}).end,250);assert.equal(selectLibraryFiles(files,{pageSize:'all'}).files.length,250);assert.equal(selectLibraryFiles(files,{filter:'saved'}).total,125);assert.equal(selectLibraryFiles(files,{sort:'size'}).files[0].size,249);assert.equal(selectLibraryFiles(files,{search:'249'}).files.length,1);assert.equal(selectLibraryFiles(files,{search:'missing',page:9}).page,0);});
test('native no-query download route returns bytes and captured frontend headers without leaking auth to signed external links',async()=>{const requests=[];const sandbox={window:{addEventListener:()=>{},fetch:async(url,options)=>{requests.push({url:String(url),headers:new Headers(options?.headers)});if(String(url).includes('/api/auth/session'))return Response.json({accessToken:'fixture-token',user:{id:scope.user}});if(String(url).includes('/files/download/file_native')&&!String(url).includes('?'))return Response.json({status:'success',download_url:'https://files.example.test/fixture',file_size_bytes:3});if(String(url).includes('files.example.test'))return new Response('abc');return Response.json({status:'error',error_code:'file_not_found'});}},location:{origin:'https://chatgpt.com',href:'https://chatgpt.com/',pathname:'/'},document:{cookie:'_account=workspace; oai-did=fixture-device',title:'Fixture',querySelector:()=>null,querySelectorAll:()=>[]},crypto:webcrypto,URL,URLSearchParams,Headers,Request,Response,AbortSignal,Uint8Array,btoa,Date,TextDecoder};vm.runInNewContext(await fs.readFile(new URL('../ChatGPT-Exporter-English-Edge/bridge.js',import.meta.url),'utf8'),sandbox);await sandbox.window.fetch('https://chatgpt.com/backend-api/fixture',{headers:{originator:'fixture', 'x-openai-web-frontend':'fixture-frontend'}});const rpc=sandbox.window.__englishExporterBridgeV242.rpc;await rpc({op:'context'});const result=await rpc({op:'assetPrepare',scope,candidates:libraryCandidates({id:'file_native'}),maxBytes:9999999});assert.equal(result.ok,true);assert.equal(result.size,3);const request=requests.find(r=>r.url.includes('/files/download/'));assert.equal(request.headers.get('originator'),'fixture');assert.equal(request.headers.get('oai-did'),'fixture-device');const external=requests.find(r=>r.url.includes('files.example.test'));assert.equal(external.headers.has('authorization'),false);assert.equal(external.headers.has('originator'),false);});
