import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {resolveBackupFolder,scanTranscriptInventory,readDetectedTranscript,mergeFolderMetadata,walkLocalFiles} from '../ChatGPT-Exporter-English-Edge/local-detection.mjs';
import {scanLocalFileCopies,localCopyCandidates,verifyLocalCopy} from '../ChatGPT-Exporter-English-Edge/local-files.mjs';
import {newJob,mergeEntry} from '../ChatGPT-Exporter-English-Edge/core.mjs';
import {Engine} from '../ChatGPT-Exporter-English-Edge/engine.mjs';
const scope={key:'local_fixture_key',user:'fixture',account:null},id='chat_local_one',hashBlob=async b=>createHash('sha256').update(Buffer.from(await b.arrayBuffer())).digest('hex'),hashData=async data=>createHash('sha256').update(JSON.stringify(data)).digest('hex');
class Dir {
 constructor(name,items={}){this.name=name;this.kind='directory';this.items=items;this.created=0;}
 async getDirectoryHandle(name,{create=false}={}){let h=this.items[name];if(!h&&create){this.created++;h=this.items[name]=new Dir(name);}if(h?.kind==='directory')return h;throw Object.assign(Error('Missing directory'),{name:'NotFoundError'});}
 async getFileHandle(name){const h=this.items[name];if(h?.kind==='file')return h;throw Object.assign(Error('Missing file'),{name:'NotFoundError'});}
 async *entries(){yield* Object.entries(this.items);}async isSameEntry(other){return this===other;}
}
const file=(name,data,size=null)=>({kind:'file',name,getFile:async()=>{const b=new Blob([typeof data==='string'?data:JSON.stringify(data)]);Object.defineProperties(b,{name:{value:name},lastModified:{value:1000},...size==null?{}:{size:{value:size}}});return b;}});
const body=(chat=id,title='Local chat',update=1)=>({conversation_id:chat,title,update_time:update,mapping:{node:{message:{author:{role:'user'},content:{parts:['local fixture']}}}}});
const idx=(key=scope.key,entries=[])=>file('conversation-index.json',{schema:'chatgpt-conversation-index/v1',scope:key,entries});
test('selecting an existing backup root does not create a nested backup',async()=>{const root=new Dir('Renamed backup',{'conversation-index.json':idx(),json:new Dir('json')});const r=await resolveBackupFolder(root,scope.key);assert.equal(r.root,root);assert.equal(root.created,0);});
test('an empty named backup root survives reconnection without nesting another root',async()=>{const root=new Dir('chatgpt-backup-'+scope.key.slice(0,12));assert.equal((await resolveBackupFolder(root,scope.key)).root,root);assert.equal(root.created,0);});
test('a parent folder detects a matching nested renamed backup and ignores a foreign one',async()=>{const good=new Dir('Renamed backup',{'conversation-index.json':idx(),json:new Dir('json')}),foreign=new Dir('Other',{'conversation-index.json':idx('other_scope')});const parent=new Dir('Downloads',{old:new Dir('old',{good,foreign})});const r=await resolveBackupFolder(parent,scope.key);assert.equal(r.root,good);assert.equal(parent.created,0);await assert.rejects(resolveBackupFolder(foreign,scope.key),/different account/);});
test('recursive body detection accepts renamed JSON, nested paths and export arrays',async()=>{const root=new Dir('Archive',{nested:new Dir('nested',{'renamed.json':file('renamed.json',body()),'conversations.json':file('conversations.json',[body('chat_array_one')])}),json:new Dir('json',{'fake_chat_bad_one.json':file('fake_chat_bad_one.json',{error:'not a transcript'})}),foreign:new Dir('foreign',{'conversation-index.json':idx('different_key'),'private.json':file('private.json',body('chat_foreign_one'))})});const scan=await scanTranscriptInventory(root,scope.key,{hashData});assert.equal(scan.files.size,2);assert.ok(!scan.files.has('chat_foreign_one'));assert.equal(scan.stats.rewrites,2);assert.equal((await readDetectedTranscript(scan.files.get('chat_array_one'))).data.conversation_id,'chat_array_one');});
test('canonical nested transcripts are parsed and credited without relying on filename UUIDs',async()=>{const root=new Dir('Backup',{json:new Dir('json',{year:new Dir('year',{'renamed.json':file('renamed.json',body())})})});const scan=await scanTranscriptInventory(root,scope.key,{hashData}),j=newJob(scope,{});mergeEntry(j,{id});await new Engine(j,{save:async()=>{}}).reconcileInventory([...scan.entries.values()]);assert.equal(j.entries[id].status,'saved');assert.equal(j.entries[id].basename,'year/renamed');});
test('detected local rewrites use the detected body before a stale browser cache and need no network',async()=>{const root=new Dir('json',{'renamed.json':file('renamed.json',body(id,'Newest body',2))}),scan=await scanTranscriptInventory(root,scope.key,{hashData}),j=newJob(scope,{library:false,attachments:false,passive:false}),writes=[];j.sources=[];const engine=new Engine(j,{save:async()=>{},cacheGet:async()=>({data:body(id,'Old cache',1)}),cachePut:async()=>{},diskRead:async key=>readDetectedTranscript(scan.files.get(key)),hash:hashData,write:async(p,s)=>writes.push([p,s]),report:async()=>{},request:async()=>{throw Error('Network must not be used');}});await engine.reconcileInventory([...scan.entries.values()]);await engine.process(j.entries[id]);assert.match(writes[0][1],/Newest body/);assert.equal(j.entries[id].status,'saved');});
test('matching portable metadata adds missing records without overwriting live failures or hashes',()=>{const j=newJob(scope,{});j.library={entries:{file_one:{status:'unavailable',parked:true}},sources:[]};const metadata={state:{job:{scope,entries:{[id]:{id,status:'saved'}},library:{entries:{file_one:{status:'pending'},file_two:{status:'saved',sha256:'a'.repeat(64)}}}}}};mergeFolderMetadata(j,metadata);assert.equal(j.library.entries.file_one.parked,true);assert.equal(j.library.entries.file_two.sha256,'a'.repeat(64));assert.ok(j.entries[id]);});
test('content paths find a renamed byte-identical local file by hash',async()=>{const sha=createHash('sha256').update('hello').digest('hex'),root=new Dir('Copies',{content:new Dir('content',{[sha]:new Dir(sha,{'different.txt':file('different.txt','hello')})})}),inv=await scanLocalFileCopies([{handle:root,source:'library'}],scope.key),asset={id:'file_test_one',name:'original.txt',size:5,remoteSha256:sha};const candidates=localCopyCandidates(inv,asset);assert.equal(candidates.length,1);assert.equal(await(await verifyLocalCopy(candidates[0],asset,inv,hashBlob)).text(),'hello');});
test('an expected hash retrieves a renamed plain file even without a prior catalog',async()=>{const sha=createHash('sha256').update('hello').digest('hex'),root=new Dir('Copies',{'renamed.txt':file('renamed.txt','hello')}),inv=await scanLocalFileCopies([{handle:root,source:'library'}],scope.key),asset={name:'original.txt',size:5,remoteSha256:sha};const candidates=localCopyCandidates(inv,asset);assert.equal(candidates.length,1);assert.ok(await verifyLocalCopy(candidates[0],asset,inv,hashBlob));});
test('selecting attachments itself resolves root-relative catalog paths within that subtree',async()=>{const sha=createHash('sha256').update('hello').digest('hex'),root=new Dir('attachments',{'renamed.txt':file('renamed.txt','hello'),'library-index.json':file('library-index.json',{scope_key:scope.key,entries:[{id:'file_native_one',path:'attachments/renamed.txt',sha256:sha}]})}),inv=await scanLocalFileCopies([{handle:root,source:'library'}],scope.key);assert.ok(await verifyLocalCopy(localCopyCandidates(inv,{id:'file_native_one',name:'Old.txt',size:5})[0],{id:'file_native_one',size:5},inv,hashBlob));});
test('prior catalog native IDs plus verified hashes allow renamed reuse; corrupted bytes fail',async()=>{const sha=createHash('sha256').update('hello').digest('hex'),root=new Dir('Backup',{attachments:new Dir('attachments',{'renamed.txt':file('renamed.txt','hello'),'library-index.json':file('library-index.json',{scope_key:scope.key,entries:[{id:'file_test_one',native_file_id:'file_test_one',path:'attachments/renamed.txt',sha256:sha}]})})}),inv=await scanLocalFileCopies([{handle:root,source:'backup'}],scope.key),asset={id:'file_test_one',name:'original.txt',size:5};const c=localCopyCandidates(inv,asset);assert.equal(c.length,1);assert.ok(await verifyLocalCopy(c[0],asset,inv,hashBlob));root.items.attachments.items['renamed.txt']=file('renamed.txt','wrong');const changed=await scanLocalFileCopies([{handle:root,source:'backup'}],scope.key);assert.equal(await verifyLocalCopy(localCopyCandidates(changed,asset)[0],asset,changed,hashBlob),null);});
test('names and sizes alone do not credit a copy; large/empty/error files are reported',async()=>{const root=new Dir('Downloads',{'one.txt':file('one.txt','hello'),'large.bin':file('large.bin','x',10000000),'empty.txt':file('empty.txt',''),'bad.txt':file('bad.txt','{"status":"error","error_code":"file_not_found"}')});const inv=await scanLocalFileCopies([{handle:root,source:'library'}],scope.key);assert.equal(localCopyCandidates(inv,{name:'one.txt',size:5}).length,0);assert.equal(inv.large,1);assert.equal(inv.invalid,2);});
test('recursive search reports limits and does not silently claim complete coverage',async()=>{const root=new Dir('Files',{'a.txt':file('a.txt','a'),'b.txt':file('b.txt','b')}),stats={};let n=0;for await(const f of walkLocalFiles(root,{maxFiles:1,stats}))n++;assert.equal(n,1);assert.equal(stats.truncated,true);});
test('hash-cache hits require the same file handle when folder names and metadata collide',async()=>{const sha=createHash('sha256').update('hello').digest('hex'),a=file('same.txt','hello'),b=file('same.txt','wrong');a.isSameEntry=async h=>h===a;b.isSameEntry=async h=>h===b;const inventory={hashCache:new Map()},asset={size:5,remoteSha256:sha},candidate=handle=>({handle,source:'same folder name',path:'same.txt',size:5});assert.ok(await verifyLocalCopy(candidate(a),asset,inventory,hashBlob));assert.equal(await verifyLocalCopy(candidate(b),asset,inventory,hashBlob),null);});
