import {retainedFileRows} from './file-links.mjs';
import {libraryIndex,libraryPath} from './library.mjs';
export const encodePath=path=>path.split('/').map(encodeURIComponent).join('/');
export const escapeHTML=text=>String(text??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function libraryFileMap(job){const map=new Map();for(const f of retainedFileRows(job)){const item={id:f.fileId || f.id,name:f.name,status:f.status,attempts:f.attempts || 0,parked:!!f.parked,error:f.error || null,path:f.path || null,expected_path:libraryPath(f),size:f.size,mime:f.mime,sha256:f.sha256,duplicate_of:f.duplicateOf || null,image_excluded:!!f.imageExcluded,source:'chatgpt-library'};for(const id of f.conversationIds || []){if(!map.has(id))map.set(id,[]);map.get(id).push(item);}}return map;}
export function conversationFiles(job,entry,map=libraryFileMap(job)){
  const library=map.get(entry.id) || [];
  const seen=new Set();return [...(entry.attachments || []),...library].filter(f=>{const key=`${f.id}:${f.name}:${f.path || ''}`;if(seen.has(key))return false;seen.add(key);return true;});
}
export function viewerHandoff(job,index,files=libraryIndex(job)){return {schema:'chatgpt-exporter-viewer/v1',version:job.version,conversation_index:'conversation-index.json',library_index:'attachments/library-index.json',manual_downloads:'attachments/manual-downloads.html',viewer:'kitomisaitichi-design/chatgpt-viewer',source_layout:'native conversation JSON, selected-branch Markdown, relative attachment paths',entries:index.entries.map(e=>({id:e.id,json:e.json,markdown:e.markdown,attachments:e.attachments || conversationFiles(job,job.entries[e.id])})),library:files.entries};}
export function catalogHTML(job,manual=false,index=libraryIndex(job)){
  const entries=manual?index.entries.filter(f=>f.status!=='saved'):index.entries;
  const rows=entries.map(f=>`<tr><td>${escapeHTML(f.name)}<small>${escapeHTML(f.id)}</small><small>Backup path: ${escapeHTML(f.expected_path)}</small></td><td>${f.size===null?'Unknown':`${(f.size/1000000).toFixed(2)} MB`}</td><td>${escapeHTML(f.status)}${f.duplicate?.isAlias?'<small>Identical content · shares one saved copy</small>':''}${f.version_info?`<small>${escapeHTML(f.version_info.reason)}${f.version_info.preferredName?' · preferred: '+escapeHTML(f.version_info.preferredName):''}</small>`:''}${f.image_excluded?'<small>Image downloads switched off</small>':''}${f.error?`<small>${escapeHTML(f.error)}</small>`:''}</td><td>${f.status==='saved'&&f.path?`<a href="../${encodePath(f.path)}" download>Open saved file</a>`:`<a href="${escapeHTML(f.manual_url)}" target="_blank" rel="noopener">Open Library folder ↗</a>`}${f.conversation_urls.map((url,i)=>`<br><a href="${escapeHTML(url)}" target="_blank" rel="noopener">Source chat ${i+1} ↗</a>`).join('')}</td></tr>`).join('');
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'"><title>ChatGPT Library ${manual?'manual downloads':'catalog'}</title><style>body{max-width:1200px;margin:40px auto;padding:0 24px;background:#101719;color:#edf4f2;font:15px/1.6 system-ui}a{color:#91debd}table{width:100%;border-collapse:collapse}td,th{padding:14px;text-align:left;border-bottom:1px solid #344348;vertical-align:top;overflow-wrap:anywhere}small{display:block;color:#a6b7b2}td:first-child{width:40%}</style><h1>ChatGPT Library ${manual?'manual downloads':'catalog'}</h1><p>Automatic downloads are strictly below 10,000,000 bytes. Files at or above 10 MB remain in the manual list. Unknown sizes are checked during a bounded download. Download links below open ChatGPT; sign in to download the original file. Save it in the indicated backup path to retain it beside your chats.</p><p>Inventory: ${index.coverage_complete?'complete':'incomplete / not yet checked'} · ${entries.length} items · <a href="${manual?'library-catalog':'manual-downloads'}.html">${manual?'All Library files':'Manual downloads'}</a></p><table><thead><tr><th>File</th><th>Size</th><th>Status</th><th>File / source</th></tr></thead><tbody>${rows}</tbody></table></html>`;
}
